version: '3'
services:
  vscode:
    image: "docker.pkg.github.com/softrams/automation-toolset/vscode-automation:v1.0.1"
    ports:
      - "8080:8080"
    environment:
     - PASSWORD=softrams
    volumes:
      - ~/coder/:/home/seluser
